from __future__ import annotations

import logging
import json
from dataclasses import dataclass
from urllib.parse import quote_plus

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from pydantic import BaseModel, Field

from shopping_app.config import get_settings
from shopping_app.db import ShoppingRepository
from shopping_app.guardrails import sanitize_query
from shopping_app.models import Marketplace, ProductCandidate, RecommendationResponse


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Structured output schemas for the LLM-based product search
# ---------------------------------------------------------------------------

class LLMProductCandidate(BaseModel):
    """A single product suggestion generated by the LLM."""
    platform: str = Field(description="One of: amazon, walmart, costco, target")
    title: str = Field(description="Full product name / model")
    estimated_price: float = Field(description="Estimated retail price in USD")
    shipping_estimate: float = Field(default=0.0, description="Estimated shipping cost (0 if free)")
    description: str = Field(description="Short description including key specs")
    reason: str = Field(description="Why this product matches the request")


class LLMProductSearch(BaseModel):
    """The complete set of product suggestions from the LLM."""
    candidates: list[LLMProductCandidate] = Field(default_factory=list)
    search_summary: str = Field(default="", description="Brief summary of the search")


class RecommendationPick(BaseModel):
    index: int = Field(ge=0)
    reason: str


class RecommendationPlan(BaseModel):
    picks: list[RecommendationPick] = Field(default_factory=list)
    rationale: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PLATFORM_DOMAIN = {
    Marketplace.AMAZON: "amazon.com",
    Marketplace.WALMART: "walmart.com",
    Marketplace.COSTCO: "costco.com",
    Marketplace.TARGET: "target.com",
}

_PRODUCT_PATH_PATTERNS = {
    Marketplace.AMAZON: ("/dp/", "/gp/product/"),
    Marketplace.WALMART: ("/ip/",),
    Marketplace.COSTCO: ("/product.", ".product."),
    Marketplace.TARGET: ("/p/",),
}

# Keywords that indicate a product should be excluded
_EXCLUDE_KEYWORDS = (
    "out of stock", "currently unavailable", "not available",
    "refurbished", "renewed", "pre-owned", "certified refurbished",
    "used", "reconditioned", "open box", "open-box",
    "restored", "seller refurbished", "manufacturer refurbished",
    "pre owned", "second hand", "secondhand",
)


def _resolve_product_url(platform: Marketplace, product_title: str) -> tuple[str, float | None]:
    """Resolve a direct product-page URL via DuckDuckGo web search.

    Returns (url, verified_price).  verified_price is the price obtained from
    search snippets or page scraping when available, or None.
    """
    import re
    from urllib.parse import urlparse

    domain = _PLATFORM_DOMAIN[platform]
    search_query = f"site:{domain} {product_title} new"
    patterns = _PRODUCT_PATH_PATTERNS[platform]

    product_url: str | None = None
    snippet_price: float | None = None

    # --- Strategy 1: DuckDuckGo site-scoped search for URL + snippet price ---
    try:
        from ddgs import DDGS
        results = DDGS().text(search_query, max_results=8)
        for r in results:
            href = r.get("href", "")
            body = (r.get("body", "") + " " + r.get("title", "")).lower()
            # Skip results whose snippet indicates out-of-stock or refurbished
            if any(kw in body for kw in _EXCLUDE_KEYWORDS):
                continue
            parsed = urlparse(href)
            host = (parsed.hostname or "").lower()
            path = parsed.path.lower()
            if domain in host and any(p in path for p in patterns):
                product_url = href
                snippet_price = _extract_snippet_price(r.get("body", ""))
                break
    except Exception:
        logger.debug("DuckDuckGo search failed for %s on %s", product_title, platform.value)

    # --- Strategy 2: Scrape product page for price (Amazon works, Target partial) ---
    if product_url and snippet_price is None:
        scraped = _scrape_page_price(product_url, platform)
        if scraped is not None:
            snippet_price = scraped

    # --- Strategy 3: Broad DuckDuckGo search (no site: restriction) for market price ---
    if snippet_price is None:
        snippet_price = _broad_search_price(product_title)

    # Fallback URL if no direct product link was found
    if not product_url:
        q = quote_plus(product_title)
        fallback_urls = {
            Marketplace.AMAZON: f"https://www.amazon.com/s?k={q}",
            Marketplace.WALMART: f"https://www.walmart.com/search?q={q}",
            Marketplace.COSTCO: f"https://www.costco.com/CatalogSearch?dept=All&keyword={q}",
            Marketplace.TARGET: f"https://www.target.com/s?searchTerm={q}",
        }
        product_url = fallback_urls.get(platform, f"https://www.google.com/search?q={q}")

    return product_url, snippet_price


_SCRAPE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}


def _scrape_page_price(url: str, platform: Marketplace) -> float | None:
    """Try to extract the primary product price from a marketplace page."""
    import re
    import requests

    try:
        resp = requests.get(url, headers=_SCRAPE_HEADERS, timeout=8)
        if resp.status_code != 200 or len(resp.text) < 1000:
            return None
        html = resp.text

        # Amazon: prices appear near "price"/"Price" keywords in the HTML
        if platform == Marketplace.AMAZON:
            # Look for price patterns near price-related context
            price_context = re.compile(
                r'(?:price|Price|priceAmount|priceToPay)["\s:>]*\$?(\d{1,5}(?:,\d{3})*\.\d{2})'
            )
            found = price_context.findall(html)
            if found:
                # Pick the most common price (mode) as the primary price
                from collections import Counter
                prices = []
                for p in found:
                    try:
                        prices.append(float(p.replace(",", "")))
                    except ValueError:
                        continue
                if prices:
                    counter = Counter(prices)
                    primary = counter.most_common(1)[0][0]
                    logger.info("Scraped Amazon price $%.2f from %s", primary, url[:80])
                    return primary

        # Target: look for current_retail in JSON data
        if platform == Marketplace.TARGET:
            m = re.search(r'"current_retail":(\d+\.?\d*)', html)
            if m:
                try:
                    price = float(m.group(1))
                    logger.info("Scraped Target price $%.2f from %s", price, url[:80])
                    return price
                except ValueError:
                    pass

    except Exception:
        logger.debug("Page scrape failed for %s", url[:80])
    return None


def _broad_search_price(product_title: str) -> float | None:
    """Search DuckDuckGo broadly (no site restriction) for price data."""
    import re

    try:
        from ddgs import DDGS
        q = f"{product_title} price buy new"
        results = DDGS().text(q, max_results=5)
        all_prices: list[float] = []
        for r in results:
            body = r.get("body", "") + " " + r.get("title", "")
            for match in re.finditer(r"\$(\d{1,5}(?:,\d{3})*\.\d{2})", body):
                try:
                    all_prices.append(float(match.group(1).replace(",", "")))
                except ValueError:
                    continue
        if all_prices:
            # Use the median price as the most reliable estimate
            all_prices.sort()
            median = all_prices[len(all_prices) // 2]
            logger.info("Broad search price $%.2f for '%s'", median, product_title)
            return median
    except Exception:
        logger.debug("Broad price search failed for '%s'", product_title)
    return None


def _extract_snippet_price(snippet: str) -> float | None:
    """Extract the first dollar price from a search-result snippet."""
    import re
    match = re.search(r"\$([\d,]+\.\d{2})", snippet)
    if match:
        try:
            return float(match.group(1).replace(",", ""))
        except ValueError:
            pass
    return None


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    import numpy as np
    a_arr, b_arr = np.array(a), np.array(b)
    denom = (np.linalg.norm(a_arr) * np.linalg.norm(b_arr))
    if denom == 0:
        return 0.0
    return float(np.dot(a_arr, b_arr) / denom)

# ---------------------------------------------------------------------------
# ShoppingRecommender — uses LLM for product discovery instead of scraping
# ---------------------------------------------------------------------------

@dataclass
class ShoppingRecommender:
    repository: ShoppingRepository

    def __post_init__(self) -> None:
        self.settings = get_settings()
        self.embeddings = OpenAIEmbeddings(
            model=self.settings.embedding_model,
            api_key=self.settings.openai_api_key,
        )
        self.llm = ChatOpenAI(
            model=self.settings.recommender_model,
            temperature=0,
            api_key=self.settings.openai_api_key,
        )

    # ---- public entry point ------------------------------------------------

    def recommend(self, query: str, session_id: str) -> RecommendationResponse:
        clean_query = sanitize_query(query)
        candidates = self._collect_candidates(clean_query)
        if not candidates:
            return RecommendationResponse(
                query=clean_query,
                recommendations=[],
                message="The recommender could not generate product suggestions. Please try rephrasing your query.",
            )

        ranked = self._rank_candidates(clean_query, candidates)
        top_items = ranked[: self.settings.max_recommendations]
        self.repository.save_recommendations(session_id, clean_query, top_items)
        return RecommendationResponse(
            query=clean_query,
            recommendations=top_items,
            message=f"Identified {len(top_items)} recommended items.",
        )

    # ---- LLM-based candidate generation ------------------------------------

    def _collect_candidates(self, query: str) -> list[ProductCandidate]:
        """Use the LLM to generate product recommendations across platforms."""
        allowed = [p for p in self.settings.allowed_platforms]
        max_per_platform = self.settings.max_candidates_per_platform

        prompt = (
            "You are a knowledgeable shopping assistant. Based on the customer's request below, "
            "suggest real, currently-available products from the specified online platforms.\n\n"
            "RULES:\n"
            "- Only suggest products from these platforms: " + ", ".join(allowed) + "\n"
            "- Suggest up to " + str(max_per_platform) + " products per platform.\n"
            "- Only include platforms that actually sell the type of product requested.\n"
            "- Use real product model names and realistic current retail prices in USD.\n"
            "- If the customer specifies brands, only suggest those brands.\n"
            "- Include estimated shipping cost (use 0 if the platform typically offers free shipping).\n"
            "- Provide a short description with key specifications.\n"
            "- CRITICAL: Do NOT include products that are Out of Stock, Currently Unavailable, "
            "Unavailable, Refurbished, Renewed, Restored, "
            "Pre-owned, Used, Reconditioned, Open Box, or Certified Refurbished.\n"
            "- Only include BRAND-NEW, currently IN-STOCK products that can be purchased right now.\n"
            "- If you are not sure whether a product is in stock, do NOT include it.\n"
            "- Provide ACCURATE current retail prices as listed on each marketplace.\n"
            "- Do NOT suggest checkout, payment, or purchase actions.\n"
            f"- Shipping destination ZIP code: {self.settings.shipping_zip}\n\n"
            f"CUSTOMER REQUEST:\n{query}"
        )

        structured = self.llm.with_structured_output(LLMProductSearch)
        try:
            result: LLMProductSearch = structured.invoke(prompt)
        except Exception:
            logger.exception("LLM product search failed")
            return []

        candidates: list[ProductCandidate] = []
        for item in result.candidates:
            try:
                platform = Marketplace(item.platform.lower().strip())
            except ValueError:
                logger.warning("LLM returned unknown platform %r, skipping", item.platform)
                continue

            url, snippet_price = _resolve_product_url(platform, item.title)
            total = item.estimated_price + item.shipping_estimate
            price_verified = False

            # Cross-check: if we obtained a real price, ALWAYS use it
            # over the LLM estimate (LLM prices are from stale training data).
            if snippet_price is not None:
                if abs(snippet_price - item.estimated_price) > 0.01:
                    logger.info(
                        "Price correction for %s: LLM $%.2f → verified $%.2f",
                        item.title, item.estimated_price, snippet_price,
                    )
                item.estimated_price = snippet_price
                total = snippet_price + item.shipping_estimate
                price_verified = True

            candidates.append(
                ProductCandidate(
                    platform=platform,
                    title=item.title,
                    url=url,
                    item_price=item.estimated_price,
                    shipping_cost=item.shipping_estimate,
                    total_cost=total,
                    description=item.description,
                    source_query=query,
                    notes=item.reason,
                    price_verified=price_verified,
                )
            )

        logger.info(
            "LLM generated %d candidates across platforms: %s",
            len(candidates),
            result.search_summary,
        )
        return [
            c for c in candidates
            if c.title
            and c.total_cost >= 0
            and not any(kw in c.title.lower() for kw in _EXCLUDE_KEYWORDS)
            and not any(kw in c.description.lower() for kw in _EXCLUDE_KEYWORDS)
        ]

    # ---- ranking with embeddings + cost normalization ----------------------

    def _rank_candidates(
        self, query: str, candidates: list[ProductCandidate]
    ) -> list[ProductCandidate]:
        query_embedding = self.embeddings.embed_query(query)
        candidate_texts = [self._candidate_text(c) for c in candidates]
        candidate_embeddings = self.embeddings.embed_documents(candidate_texts)

        semantic_scores = [
            _cosine_similarity(query_embedding, ce)
            for ce in candidate_embeddings
        ]

        min_cost = min(c.total_cost for c in candidates)
        max_cost = max(c.total_cost for c in candidates)
        cost_spread = max(max_cost - min_cost, 1e-6)

        for candidate, sem_score in zip(candidates, semantic_scores):
            cost_score = 1.0 - ((candidate.total_cost - min_cost) / cost_spread)
            candidate.score = round(0.7 * sem_score + 0.3 * cost_score, 4)

        sorted_candidates = sorted(
            candidates, key=lambda item: (item.score, -item.total_cost), reverse=True
        )

        plan = self._choose_top(query, sorted_candidates)
        chosen: list[ProductCandidate] = []
        for pick in plan.picks[: self.settings.max_recommendations]:
            if 0 <= pick.index < len(sorted_candidates):
                item = sorted_candidates[pick.index]
                item.notes = pick.reason
                chosen.append(item)

        if len(chosen) < self.settings.max_recommendations:
            for item in sorted_candidates:
                if item not in chosen:
                    chosen.append(item)
                if len(chosen) == self.settings.max_recommendations:
                    break

        return chosen

    # ---- LLM final pick ---------------------------------------------------

    def _choose_top(
        self, query: str, candidates: list[ProductCandidate]
    ) -> RecommendationPlan:
        candidate_summary = []
        for idx, item in enumerate(candidates[:10]):
            candidate_summary.append(
                {
                    "index": idx,
                    "platform": item.platform.value,
                    "title": item.title,
                    "price": item.item_price,
                    "shipping": item.shipping_cost,
                    "total": item.total_cost,
                    "url": item.url,
                    "description": item.description[:300],
                    "score": item.score,
                }
            )

        prompt = (
            "You are ranking shopping items for a customer. Pick the top "
            f"{self.settings.max_recommendations} items that best match the request.\n"
            "Prefer lower total cost including shipping, reputable platforms, and relevance to the request.\n"
            "Never suggest checkout or payment steps. Return indices from the provided candidate list only.\n\n"
            f"Request: {query}\n"
            f"Candidates: {json.dumps(candidate_summary, ensure_ascii=False)}"
        )
        structured = self.llm.with_structured_output(RecommendationPlan)
        try:
            return structured.invoke(prompt)
        except Exception:
            return RecommendationPlan(
                picks=[
                    RecommendationPick(index=i, reason="Best semantic and cost fit")
                    for i in range(min(self.settings.max_recommendations, len(candidates)))
                ]
            )

    # ---- helpers -----------------------------------------------------------

    @staticmethod
    def _candidate_text(candidate: ProductCandidate) -> str:
        return f"{candidate.title} — {candidate.description} (${candidate.total_cost:.2f} on {candidate.platform.value})"
